### ISSUE TITLE
Upgrade nokogiri to version >= 1.13.6

### ISSUE THREAD

**Issue by authiatr** [azohra/forsis#16]
Hello,

We've got a warning about the `nokogiri` dependency. 
Do you plan to update `nokogiri` soon?
![image](https://user-images.githubusercontent.com/10559183/173314874-27bcdf03-561b-4fe7-a8c2-ff52d137b29e.png)

**Comment by Azbagheri** [comment]
Hi @authiatr ,
We have migrated forsis over to a new organization and this security alert has been remediated in the latest version of forsis ( v0.4.0 ). Please check the [new repo](https://github.com/Tumiya/forsis) for future updates and requests.

**Comment by authiatr** [comment]
Thank you for your quick reply.
