### ISSUE TITLE
Upgrade nokogiri to version 1.12.5 or later

### ISSUE THREAD

**Issue by aelam** [azohra/forsis#7]
we've got a warning about `nokogiri`, Do you have any schedule of updating `nokogiri`

  spec.add_dependency('nokogiri', '~> 1.11.0'
![Screen Shot 2021-12-20 at 13 27 41](https://user-images.githubusercontent.com/232337/146711794-cffac539-77cb-4ec3-b402-8f791e798fb2.png)
)

**Comment by aelam** [comment]
@Azbagheri  It seems you've updated nokogiri in master branch, Could you tag it and release a new version

**Comment by Azbagheri** [comment]
@aelam yeah, I've already started the release process. The new version will come out today!

**Comment by Azbagheri** [comment]
@aelam Forsis v0.2.0 has been released to RubyGems!! Going forward, I'll be creating releases on Github as well. 
You can access the release notes for Forsis v0.2.0 [here](https://github.com/azohra/forsis/releases).
